# Generated by Django 4.1.1 on 2022-11-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_biodata_kode_kasir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='kode_kasir',
            field=models.CharField(max_length=10),
        ),
    ]
