# Generated by Django 4.1.1 on 2022-09-27 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kasir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='laporan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('folder', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kode_kasir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.kasir')),
            ],
        ),
    ]
