# Generated by Django 4.1.1 on 2022-10-10 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_kasir_options_alter_laporan_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laporan',
            old_name='folder',
            new_name='upload_file',
        ),
    ]
