# Generated by Django 4.1.1 on 2022-10-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_laporan_options_alter_laporan_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='nama',
            field=models.CharField(max_length=100),
        ),
    ]
