# Generated by Django 4.1.1 on 2022-10-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_laporan_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='upload_file',
            field=models.FileField(null=True, upload_to='file/'),
        ),
    ]
