# Generated by Django 4.1.1 on 2022-11-11 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0007_alter_laporan_upload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasir',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kasir', to=settings.AUTH_USER_MODEL),
        ),
    ]
