# Generated by Django 4.1.1 on 2022-11-11 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_kasir_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='kode_kasir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='dashboard.kasir'),
        ),
    ]
